Feature/gh1 updating platform hal file for telco voip manager
rdkcentral/rdkb-halif-platform pull request #8
Opened 2024-05-29 13:41 UTC by biju-vi

2024-05-29 15:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdkb-halif-platform?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdkb-halif-platform?pullRequest=8) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: biju-vi<br/>:white_check_mark: sbarre01<br/>:x: BVE07<br/><hr/>**BVE07** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdkb-halif-platform?pullRequest=8) it.</sub>

2024-05-29 15:17 UTC, biju-vi commented
platform_hal_getEcoModeStatus has been added because of "rebase" happened with main branch

2024-05-30 01:32 UTC, anoopchelakkode requested changes
We should't put wifi related APIs in platform_hal. Please use wifi hal for these apis.

2024-07-31 10:53 UTC, Ulrond commented on include/platform_hal.h
> +INT platform_hal_getEcoModeStatus(INT radioIndex, INT *pValue);
```c
/**
 * @brief Retrieves the ECO mode status of a WiFi radio module.
 *
 * @param[in] radioIndex -  Index of the radio module to query (0 for 2.4GHz, 1 for 5GHz).
 * @param[out] pValue    - Pointer to an integer to store the ECO mode status (0: disabled, 1: enabled).
 *
 * @returns The status of the operation.
 * @retval RETURN_OK if successful.
 * @retval RETURN_ERR if an error occurs.
 */
INT platform_hal_getEcoModeStatus(INT radioIndex, INT *pValue);
```

2024-07-31 10:55 UTC, Ulrond commented
> _ No description provided. _

please update description on why this change is occuring.
- Also I assume that you've tagged the source point of where the sync occurred on gerrit?
- This will be a minor release because it's an upgrade of functionality, the testing suite should still work, just not test this function.
- You will need to upgrade the testing suite of course to support testing of this function also.

2024-08-02 17:07 UTC, Ulrond commented on include/platform_hal.h
> +#ifdef FEATURE_RDKB_TELCOVOICE_MANAGER
don't use compile switches in the interfaces, the interface must work on all platforms exactly the same.

Add a return CODE to support NOT_SUPPORTED, so dynamically the lower layer can tell you that it's not supported dynamically.

2024-08-02 18:34 UTC, Ulrond requested changes
comment improvements

2024-08-02 18:34 UTC, Ulrond commented on include/platform_hal.h
> +INT platform_hal_VoiceGetFRStatus(BOOLEAN *pIsFRTriggered);
```c
/**
 * @brief Retrieves the Voice Hard Factory Reset status.
 *
 * @param[out] pIsFRTriggered Pointer to a BOOLEAN variable to store the FR status 
 *                           (TRUE if triggered, FALSE if not).
 *
 * @returns The status of the operation.
 * @retval RETURN_OK if the status flag was successfully retrieved.
 * @retval RETURN_ERR if an error occurred.
 */
INT platform_hal_VoiceGetFRStatus(BOOLEAN *pIsFRTriggered);
```

2024-08-02 18:34 UTC, Ulrond commented on include/platform_hal.h
> +INT platform_hal_VoiceResetFRStatus();
```c
/**
 * @brief Resets the Voice Hard Factory Reset status.
 *
 * @returns The status of the operation.
 * @retval RETURN_OK if the status flag was successfully reset.
 * @retval RETURN_ERR if the status flag could not be reset.
 */
INT platform_hal_VoiceResetFRStatus();
```

2024-09-20 13:36 UTC, Ulrond commented
what's happening with this, can we reject the merge? @biju-vi  and close it ?

2024-10-09 11:04 UTC, Ulrond commented
@biju-vi - should this PR be closed, and the branch deleted?

2024-11-18 04:04 UTC, closed without merging